export const ASSESSMENT_CATEGORIES = [
  { id: 'aptitude', label: 'Aptitude', description: 'Quantitative and logical reasoning', color: 'violet' },
  { id: 'dsa', label: 'Data structures & algorithms', description: 'Problem solving and complexity', color: 'blue' },
  { id: 'coreCS', label: 'Core computer science', description: 'OS, databases, networks, and OOP', color: 'green' },
  { id: 'hr', label: 'HR & behavioral', description: 'Workplace judgment and communication', color: 'orange' },
];

export const ASSESSMENT_QUESTIONS = [
  { category: 'aptitude', topic: 'Percentages', prompt: 'A product priced at ₹800 is discounted by 15%. What is its sale price?', options: ['₹660', '₹680', '₹700', '₹720'], answer: 1, explanation: '15% of ₹800 is ₹120. Subtracting the discount gives ₹680.' },
  { category: 'aptitude', topic: 'Percentages', prompt: 'A salary rises from ₹40,000 to ₹46,000. What is the percentage increase?', options: ['12%', '15%', '18%', '20%'], answer: 1, explanation: 'The increase is ₹6,000; ₹6,000 ÷ ₹40,000 = 15%.' },
  { category: 'aptitude', topic: 'Ratios', prompt: 'The ratio of developers to designers is 3:2. If there are 25 people, how many are developers?', options: ['10', '12', '15', '18'], answer: 2, explanation: 'There are 5 total parts, so each part is 5 people. Developers make up 3 × 5 = 15.' },
  { category: 'aptitude', topic: 'Ratios', prompt: 'A and B share ₹840 in the ratio 4:3. How much does B receive?', options: ['₹320', '₹360', '₹420', '₹480'], answer: 1, explanation: 'Seven parts make ₹840, so each part is ₹120. B receives 3 parts, or ₹360.' },
  { category: 'aptitude', topic: 'Number patterns', prompt: 'What number comes next: 3, 7, 15, 31, …?', options: ['47', '55', '62', '63'], answer: 3, explanation: 'Each term is doubled and then increased by 1: 31 × 2 + 1 = 63.' },
  { category: 'aptitude', topic: 'Number patterns', prompt: 'A car travels 150 km in 3 hours at a constant speed. How far will it travel in 5 hours?', options: ['200 km', '225 km', '250 km', '300 km'], answer: 2, explanation: 'Its speed is 50 km/h, so in 5 hours it covers 250 km.' },

  { category: 'dsa', topic: 'Arrays & hashing', prompt: 'Which data structure gives average O(1) lookup by key?', options: ['Hash table', 'Sorted array', 'Linked list', 'Binary heap'], answer: 0, explanation: 'A hash table computes an index from the key, giving average constant-time lookup (with a suitable hash function).' },
  { category: 'dsa', topic: 'Arrays & hashing', prompt: 'You need to find whether an array contains two values that sum to a target. Which approach is O(n) on average?', options: ['Compare every pair', 'Sort, then scan with two pointers', 'Track complements in a hash set', 'Run binary search for every value'], answer: 2, explanation: 'For each value, check whether its complement has already been seen in a hash set. This takes O(n) average time.' },
  { category: 'dsa', topic: 'Trees & graphs', prompt: 'Which traversal of a binary search tree visits keys in sorted order?', options: ['Preorder', 'Inorder', 'Postorder', 'Level order'], answer: 1, explanation: 'Inorder traversal visits the left subtree, node, then right subtree. BST ordering makes the result sorted.' },
  { category: 'dsa', topic: 'Trees & graphs', prompt: 'Which algorithm finds shortest paths from one source in an unweighted graph?', options: ['Depth-first search', 'Breadth-first search', 'Kruskal’s algorithm', 'Topological sort'], answer: 1, explanation: 'BFS explores vertices by distance in edges, so the first visit gives a shortest path in an unweighted graph.' },
  { category: 'dsa', topic: 'Complexity & algorithms', prompt: 'What is the worst-case time complexity of merge sort?', options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(n²)'], answer: 2, explanation: 'Merge sort splits the input into logarithmically many levels and processes all n values at each level: O(n log n).' },
  { category: 'dsa', topic: 'Complexity & algorithms', prompt: 'Which technique is most suitable when a problem has overlapping subproblems and optimal substructure?', options: ['Greedy selection', 'Dynamic programming', 'Linear search', 'Randomized pivoting'], answer: 1, explanation: 'Dynamic programming stores solutions to repeated subproblems and combines them using optimal substructure.' },

  { category: 'coreCS', topic: 'Databases & SQL', prompt: 'What does a database index primarily help improve?', options: ['Read/query lookup speed', 'The number of columns in a table', 'Password encryption', 'Network bandwidth'], answer: 0, explanation: 'An index helps the database find rows faster, though indexes require storage and can add write overhead.' },
  { category: 'coreCS', topic: 'Databases & SQL', prompt: 'Which normal form removes partial dependencies on part of a composite key?', options: ['First normal form', 'Second normal form', 'Third normal form', 'Boyce–Codd normal form'], answer: 1, explanation: 'Second normal form requires 1NF and that every non-key attribute depend on the whole candidate key.' },
  { category: 'coreCS', topic: 'Operating systems', prompt: 'Which condition is necessary for a deadlock to occur?', options: ['Mutual exclusion', 'High CPU utilization', 'A page fault', 'A process having no resources'], answer: 0, explanation: 'Mutual exclusion is one of the four Coffman conditions. All four conditions must hold for deadlock.' },
  { category: 'coreCS', topic: 'Operating systems', prompt: 'What is the main purpose of virtual memory?', options: ['Make the CPU run at a higher clock speed', 'Give processes a larger logical address space than physical RAM', 'Replace the file system', 'Prevent all cache misses'], answer: 1, explanation: 'Virtual memory maps process address spaces onto physical memory and storage, providing isolation and flexibility.' },
  { category: 'coreCS', topic: 'Networks & OOP', prompt: 'Which transport protocol provides ordered, reliable byte-stream delivery?', options: ['IP', 'UDP', 'TCP', 'ARP'], answer: 2, explanation: 'TCP provides reliable, ordered byte-stream delivery through acknowledgements, sequencing, and retransmission.' },
  { category: 'coreCS', topic: 'Networks & OOP', prompt: 'In object-oriented programming, what does polymorphism allow?', options: ['One interface to have different implementations', 'A class to have no methods', 'Data to be stored only in arrays', 'A program to skip type checking'], answer: 0, explanation: 'Polymorphism lets code work through a shared interface while different object types provide their own behavior.' },

  { category: 'hr', topic: 'Communication', prompt: 'A teammate’s update is unclear and a deadline is near. What is the most useful first response?', options: ['Assume the work is late and escalate immediately', 'Ask a focused question to clarify status and blockers', 'Wait until the deadline passes', 'Redo their work without telling them'], answer: 1, explanation: 'A focused, respectful question surfaces the facts and any blocker early, so the team can agree on next steps.' },
  { category: 'hr', topic: 'Communication', prompt: 'You realize you gave your manager an incorrect estimate. What should you do?', options: ['Hope the task finishes within the original estimate', 'Update them promptly with the new estimate and reason', 'Change the project plan without mentioning it', 'Blame the requirements'], answer: 1, explanation: 'Timely, clear communication lets others adjust plans and shows accountability.' },
  { category: 'hr', topic: 'Teamwork', prompt: 'Two teammates disagree about an implementation. How can you help the discussion move forward?', options: ['Choose the more senior person’s idea automatically', 'Compare both options against shared requirements and evidence', 'Keep both implementations indefinitely', 'Avoid discussing the disagreement'], answer: 1, explanation: 'Returning to requirements and evidence keeps the conversation collaborative and focused on the outcome.' },
  { category: 'hr', topic: 'Teamwork', prompt: 'You finish your task early while a teammate is blocked. What is a constructive next step?', options: ['Offer specific help after checking priorities with the team', 'Take over their task without asking', 'Wait silently for more work', 'Tell the manager the teammate is too slow'], answer: 0, explanation: 'Offer help respectfully and coordinate priorities so you support the team without disrupting ownership.' },
  { category: 'hr', topic: 'Ownership & learning', prompt: 'A reviewer points out a mistake in your code. What response is most effective?', options: ['Explain why the reviewer should have caught it', 'Understand the issue, fix it, and note how to prevent it next time', 'Ignore the comment if the code runs', 'Remove the review request'], answer: 1, explanation: 'Addressing the issue and learning from it demonstrates ownership and improves future work.' },
  { category: 'hr', topic: 'Ownership & learning', prompt: 'You are assigned a task using a tool you have not used before. What is a strong first step?', options: ['Wait until someone gives you a complete tutorial', 'Clarify the goal, explore reliable documentation, and share risks early', 'Pretend you already know it', 'Decline without investigating'], answer: 1, explanation: 'Clarifying the outcome, learning independently, and raising risks early balances initiative with transparency.' },
];
